CREATE TABLE bridge_node (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE COMMENT '节点名称',
    token_hash VARCHAR(128) NOT NULL COMMENT '认证 token 的 SHA-256 散列',
    status VARCHAR(16) NOT NULL DEFAULT 'DISCONNECTED' COMMENT 'CONNECTED / DISCONNECTED',
    registered_tools JSON DEFAULT NULL COMMENT '节点注册时上报的可用工具列表',
    last_connected_at DATETIME DEFAULT NULL,
    last_heartbeat_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE agent ADD COLUMN bridge_node VARCHAR(64) DEFAULT NULL COMMENT '绑定的 Bridge 节点名称';
